homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index_page, name='index'),
    path('article/', views.articles, name='articles'),
]

myproj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('homepage/', include('homepage.urls')),
]

article/models.py
from django.db import models



class Author(models.Model):
  name = models.CharField(max_length=255)
  email = models.EmailField()

class Article(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    body = models.TextField()
    author = models.ForeignKey('Author', related_name='articles', on_delete=models.CASCADE)

homepage/models.py
from django.db import models

# Create your models here.

article/views.py
from django.shortcuts import render

# Create your views here.

homepage/views.py
from django.shortcuts import render
from django.views.decorators.http import require_GET

def index_page(request):
    response = render(request, 'homepage/index.html')
    response['MyCustomHeader'] = 'spam-and-eggs 42'
    return response


@require_GET
def articles(request):
    my_obj = MyClass()
    args = {'articles': list(range(1,5)), 'users':list([]), 'obj': my_obj}
    return render(request, 'homepage/articles.html', args)


class MyClass:
    foo = 42
    bar = 50


    def __repr__(self):
        return f'<MyClass {self.foo} {self.bar}>'

homepage/templates/homepage/articles.html
{% extends 'homepage/base.html' %}
{% block title %}
<title> Hello, Artie!</title>
{% endblock %}

{% block body %}

    <h1>Articles page!!!</h1>
    {{ articles }}

    {% for num in articles  %}
         {% if num == 1 %}
       <h1> Sosiska {{ num }}</h1>

        {% else %}
<div> Arti {{ num }}</div>
{% endif %}
{% endfor %}

  {% for num2 in users %}

  <div>{{ num2 }}</div>
  {% empty %}
 <div>Pustota</div>
{% endfor %}

    <ul class="list-group"></ul>
    {% for num in articles %}
        <li class="list-group-item  {% cycle 'list-group-item-success' 'list-group-item-secondary' %}">art № {{num}}</li>
    {% endfor %}
    {% comment %}
    <li class="list-group-item list-group-item-warning">art № num</li>
    <li class="list-group-item list-group-item-info">A simple info list group item</li>

    {% endcomment %}
<div>{{ obj }}</div>
    {% if obj.foo < obj.bar %}
    <div>{{ obj.foo }} > bar</div>
    {% endif %}
{% endblock %}

homepage/templates/homepage/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% load static %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css\bootstrap.css' %}">
    <div class="container">
  
        {% block title %}
        <title> Hello, homepage!</title>
        {% endblock %}
    <div>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li>
          </ul>
        </div>
      </nav>

    {% block body %}
    <h1>Override me!!!</h1>
    {% endblock %}

    
        <a href="{% url 'homepage:articles' %} "> Visit articles!</a>
        <a href="{% url 'homepage:index' %} "> Visit index!</a>

    <script src="{% static 'js\jquery.js' %}"></script>

    <script src="{% static 'js\bootstrap.min.js' %} "></script>
      </div>

homepage/templates/homepage/index.html
{% extends 'homepage/base.html' %}
{% block title %}
<title> Hello, INdi!</title>
{% endblock %}


{% block body %}
<h1>Index OLOLOL page!!!</h1>
{% endblock %}